dist: trusty
language: go
go:
  - "1.10"

services:
  - postgresql
  - mysql

addons:
  postgresql: "9.6"

before_install:
  - mysql -e 'CREATE DATABASE svcproxy;'
  - psql -c 'create database svcproxy;' -U postgres

script:
    - make test build-linux-amd64
