---
listener:
  httpAddr: :8080
  httpsAddr: :8443
autocert:
  cache:
    backend: sql
    backendOptions:
      dsn: root@tcp(127.0.0.1:3306)/svcproxy
      encryptionKey: testkey
services:
  - frontend:
      fqdn: myservice.local
    backend:
      url: http://localhost:8082
