---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: svcproxy
  name: svcproxy
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: svcproxy
  type: LoadBalancer
